'use client'

import Link from 'next/link'
import { useEffect,useState } from 'react'
import { ArrowLeft,ArrowRight,Package,Phone,Truck } from 'lucide-react'
import { AdminShell,Avatar,StatusBadge } from '@/components/layout/admin-shell'

type Delivery={id:number;client:string;phone:string;from:string;to:string;courier:string;status:string;price:number;time:string}
const money=(n:number)=>new Intl.NumberFormat('fr-FR').format(Math.round(n))+' FCFA'
const label=(s:string)=>({en_attente:'En attente',en_cours:'En cours',livre:'Livrée',retour:'Retour',echec:'Échec'}[s]??s)

export function DeliveriesModulePage(){
 const [data,setData]=useState<Delivery[]>([]),[q,setQ]=useState(''),[status,setStatus]=useState(''),[loading,setLoading]=useState(true)
 const load=()=>{setLoading(true);const p=new URLSearchParams();if(q)p.set('q',q);if(status)p.set('status',status);fetch('/api/admin/deliveries?'+p.toString(),{cache:'no-store'}).then(r=>r.json()).then(x=>setData(x.data??[])).finally(()=>setLoading(false))}
 useEffect(()=>{const t=setTimeout(load,250);return()=>clearTimeout(t)},[q,status])
 return <AdminShell title="Livraisons" subtitle="Toutes les livraisons réelles de Bimbim."><div className="rounded-2xl border border-border bg-card overflow-hidden"><div className="flex flex-col gap-3 border-b border-border p-5 md:flex-row"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Rechercher..." className="flex-1 rounded-xl border border-border bg-background px-3 py-2.5 text-sm outline-none"/><select value={status} onChange={e=>setStatus(e.target.value)} className="rounded-xl border border-border bg-background px-3 py-2.5 text-sm"><option value="">Tous les statuts</option><option value="en_attente">En attente</option><option value="en_cours">En cours</option><option value="livre">Livrée</option><option value="retour">Retour</option><option value="echec">Échec</option></select></div>{loading?<div className="p-10 text-center text-sm text-muted-foreground">Chargement...</div>:data.length===0?<div className="p-10 text-center text-sm text-muted-foreground">Aucune livraison trouvée.</div>:<div className="divide-y divide-border">{data.map(d=><Link href={`/deliveries/${d.id}`} key={d.id} className="grid gap-3 px-5 py-4 hover:bg-muted/30 md:grid-cols-[90px_1fr_1fr_1fr_120px_100px] md:items-center"><span className="font-mono text-xs font-semibold text-primary">#{d.id}</span><div><p className="text-sm font-medium">{d.client}</p><p className="text-xs text-muted-foreground">{d.phone}</p></div><span className="truncate text-sm">{d.from}</span><span className="truncate text-sm">{d.to}</span><span className="truncate text-sm">{d.courier}</span><div><StatusBadge status={label(d.status)}/><p className="mt-1 text-xs text-muted-foreground">{money(d.price)}</p></div></Link>)}</div>}</div></AdminShell>
}

export function DeliveryModuleDetailPage(){
 const [d,setD]=useState<any>(null),[loading,setLoading]=useState(true)
 useEffect(()=>{const id=window.location.pathname.split('/').pop();fetch('/api/admin/deliveries/'+id,{cache:'no-store'}).then(r=>r.json()).then(setD).finally(()=>setLoading(false))},[])
 if(loading)return <AdminShell title="Livraison" subtitle=""><div className="p-10 text-center text-sm text-muted-foreground">Chargement...</div></AdminShell>
 if(!d?.id)return <AdminShell title="Livraison" subtitle=""><div className="p-10 text-center text-sm text-danger">Livraison introuvable.</div></AdminShell>
 const c=d.courier
 return <AdminShell title={`Livraison #${d.id}`} subtitle="Détail réel de la livraison"><Link href="/deliveries" className="mb-5 inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground"><ArrowLeft className="size-4"/>Retour</Link><div className="grid gap-6 lg:grid-cols-[1fr_.7fr]"><div className="space-y-6"><section className="rounded-2xl border border-border bg-card p-6"><div className="flex flex-wrap justify-between gap-3"><div><p className="text-sm text-muted-foreground">Trajet</p><h2 className="mt-2 text-xl font-semibold">{d.from}<ArrowRight className="mx-2 inline size-5 text-muted-foreground"/>{d.to}</h2></div><StatusBadge status={label(d.status)}/></div><div className="mt-6 grid gap-5 border-t border-border pt-5 sm:grid-cols-2"><div><p className="text-xs text-muted-foreground">Client</p><p className="mt-1 font-medium">{d.client?.nom??'—'}</p><p className="text-sm text-muted-foreground">{d.client?.telephone}</p></div><div><p className="text-xs text-muted-foreground">Coursier</p><div className="mt-1 flex items-center gap-2">{c?<><Avatar initials={`${c.prenom?.[0]??''}${c.nom?.[0]??''}`}/><span>{c.prenom} {c.nom}</span></>:<span className="text-muted-foreground">Non assigné</span>}</div></div><div><p className="text-xs text-muted-foreground">Service</p><p className="mt-1 font-medium">{d.service}</p></div><div><p className="text-xs text-muted-foreground">Prix</p><p className="mt-1 font-semibold">{money(d.price)}</p></div></div></section><section className="rounded-2xl border border-border bg-card p-6"><h2 className="font-semibold">Segments</h2><div className="mt-4 divide-y divide-border">{d.segments?.map((s:any)=><div key={s.id} className="py-3"><div className="flex justify-between"><b className="text-sm">{s.type}</b><span className="text-xs text-muted-foreground">{s.status}</span></div><p className="mt-1 text-xs text-muted-foreground">{s.from} → {s.to}</p></div>)}</div></section></div><aside className="rounded-2xl border border-border bg-card p-5"><h2 className="font-semibold">Informations</h2><div className="mt-4 space-y-4 text-sm"><div><p className="text-xs text-muted-foreground">Destinataire</p><p>{d.recipient?.name}</p><p className="text-muted-foreground">{d.recipient?.phone}</p></div><div><p className="text-xs text-muted-foreground">Distance</p><p>{d.distanceKm??'—'} km</p></div><div><p className="text-xs text-muted-foreground">Créée le</p><p>{new Date(d.createdAt).toLocaleString('fr-FR')}</p></div></div></aside></div></AdminShell>
}
